decentraland/profile

- package-lock.json
- package.json
- tsconfig.json
- vite.config.ts
This PR fixes the production build by adding the Node JS polyfills.
Closes #11
> fix: Make deployment build functional

- package-lock.json
- package.json
- public/package.json
- scripts/prebuild.js
- tsconfig.json
This PR adds the pre-build scripts to set the BASE URL to the CDN when building the production version of the UI.
> fix: Use CDN public path

- .github/workflows/build-release.yaml
- package-lock.json
This PR disables provenance to fix the deployment issue.
> fix: Disable provenance

- package-lock.json
- package.json
- src/modules/config/env/dev.json
This PR adds support for Sepolia.
> feat: Add support for Sepolia

- src/components/FriendshipButton/FriendshipButton.container.ts
- src/components/FriendshipButton/FriendshipButton.types.ts
- src/modules/social/actions.ts
- src/modules/social/reducer.spec.ts
- src/modules/social/reducer.ts
- src/modules/social/sagas.spec.ts
- src/modules/social/sagas.ts
- src/modules/social/selectors.spec.ts
- src/modules/social/selectors.ts
This PR adds the accept and the reject friendship functionality and attaches it to the `FriendshipButton`.
Closes #16
> feat: Accept / reject friendship

- src/components/FriendshipButton/FriendshipButton.container.ts
- src/components/FriendshipButton/FriendshipButton.spec.tsx
- src/components/FriendshipButton/FriendshipButton.tsx
- src/components/FriendshipButton/FriendshipButton.types.ts
- src/modules/social/actions.ts
- src/modules/social/reducer.spec.ts
- src/modules/social/reducer.ts
- src/modules/social/sagas.spec.ts
- src/modules/social/sagas.ts
- src/modules/social/selectors.spec.ts
- src/modules/social/selectors.ts
This PR adds the add and remove friends functionality.
Closes #59 
Closes #17
> feat: Add and remove friends

- src/modules/social/actions.ts
- src/modules/social/client.ts
- src/modules/social/reducer.spec.ts
- src/modules/social/reducer.ts
- src/modules/social/sagas.spec.ts
- src/modules/social/sagas.ts
- src/modules/social/selectors.spec.ts
- src/modules/social/selectors.ts
This PR adds the mutual friends fetching logic.
Closes #56
> feat: Add mutual friends logic

- src/components/FriendshipButton/FriendshipButton.container.ts
- src/components/FriendshipButton/FriendshipButton.types.ts
- src/modules/social/actions.ts
- src/modules/social/reducer.spec.ts
- src/modules/social/reducer.ts
- src/modules/social/sagas.spec.ts
- src/modules/social/sagas.ts
- src/modules/social/selectors.spec.ts
- src/modules/social/selectors.ts
This PR adds the cancel friendship functionality.
Closes #60
> feat: Cancel friendship

- src/components/ProfileInformation/ProfileInformation.tsx
This PR fixes the `ProfileInformation` component by giving the `Profile` component the avatar to load it.
It also fixes the URLs and the user address.
> fix: Profile information not showing up

- src/components/ProfileInformation/ProfileInformation.tsx
- src/main.tsx
- src/modules/routing/locations.ts
This PR changes the sites handle to load accounts in the `/accounts/` path.
> feat: Change handle to accounts

- package-lock.json
- package.json
- src/utils/view.ts
This PR upgrades the packages:
* decentraland-ui
* decentraland-dapps
* @dcl/eslint-config
> chore: Upgrade decentraland UI package

- src/components/Overview/Overview.container.ts
- src/components/Overview/Overview.module.css
- src/components/Overview/Overview.tsx
- src/components/Overview/Overview.types.ts
- src/components/Pages/MainPage/MainPage.tsx
- src/modules/translation/locales/en.json
- src/modules/translation/locales/es.json
- src/modules/translation/locales/zh.json
> fix: empty message on profile overview

- src/components/ProfileInformation/ProfileInformation.tsx
> fix: Truncate address differently

- src/components/FriendsCounter/FriendsCounter.container.ts
> fix: Friends counter dispatch

- src/components/FriendshipButton/FriendshipButton.module.css
- src/components/FriendshipButton/FriendshipButton.tsx
Closes #115
Closes #117
Closes #123
> fix: Friend button styles

- src/components/ProfileInformation/ProfileInformation.tsx
> fix: Icon inconsistency

- src/components/AvatarLink/AvatarLink.tsx
- src/components/Modals/AboutModal/AboutModal.tsx
- src/components/Overview/Overview.tsx
- src/components/ProfileInformation/ProfileInformation.tsx
- src/modules/translation/locales/en.json
- src/modules/translation/locales/es.json
- src/modules/translation/locales/zh.json
> feat: Add missing popups

- src/components/ProfileInformation/ProfileInformation.tsx
> fix: Open profile in new tab

- src/main.tsx
Whenever a path is not typed correctly, redirect users to the default account page.
> fix: Redirect user to default page

- src/components/Overview/Overview.module.css
- src/components/Overview/Overview.tsx
- src/components/Pages/MainPage/MainPage.module.css
- src/components/Pages/MainPage/MainPage.tsx
> fix: Overview without items

- src/components/ProfileInformation/ProfileInformation.module.css
- src/components/ProfileInformation/ProfileInformation.tsx
- src/index.css
> fix: Profile number color

- src/components/Avatar/Avatar.module.css
- src/components/PageLayout/PageLayout.module.css
- src/components/PageLayout/PageLayout.tsx
- src/components/Pages/MainPage/MainPage.module.css
- src/components/Pages/MainPage/MainPage.tsx
closes #106 
closes #132 
closes #161
> fix: scroll behaviour

- jest.config.ts
- package-lock.json
- package.json
- src/components/PageLayout/PageLayout.module.css
- src/components/Pages/SignInPage/SignInPage.module.css
- src/components/Pages/SignInPage/SignInPage.tsx
This PR fixes the mobile sign in styles.
It does break some mobile styles when setting the `PageLayout` as 100%.
Closes #169
Closes #172
> fix: Mobile sign in styles

- src/components/Pages/MainPage/MainPage.module.css
- src/components/ProfileInformation/ProfileInformation.module.css
- src/index.css
Closes #178
Closes #174
Closes #175
> fix: Mobile style fixes

- src/components/ProfileInformation/ProfileInformation.tsx
- src/components/WorldsButton/WorldsButton.tsx
> fix: Show worlds tooltip only when worlds are live

- src/components/ProfileInformation/ProfileInformation.module.css
> fix: friends button

- src/components/FriendshipButton/FriendshipButton.module.css
- src/components/FriendshipButton/FriendshipButton.tsx
Closes #157
Closes #147
Closes #177
> fix: FriendsButton hover and focus

- src/components/Overview/Overview.module.css
> fix: cards size on desktop

- src/components/ProfileInformation/ProfileInformation.tsx
> fix: Remove wrong popup

- src/components/ProfileInformation/ProfileInformation.module.css
- src/components/ProfileInformation/ProfileInformation.tsx
- src/components/WorldsButton/WorldsButton.module.css
- src/components/WorldsButton/WorldsButton.tsx
- src/index.css
> fix: Invert worlds and share buttons

- src/main.tsx
This PR fixes action tracking by importing the track file.
> fix: Enable action tracking

- src/components/Avatar/Avatar.module.css
- src/components/ProfileInformation/ProfileInformation.module.css
- src/components/ProfileInformation/ProfileInformation.tsx
- src/components/ProfileInformation/constants.ts
> fix: fixed profile information components structure

- src/components/Avatar/Avatar.module.css
- src/components/Pages/MainPage/MainPage.module.css
So it now looks something like this:
> fix: Update avatar preview styles

- src/lib/MarketplaceGraphClient.spec.ts
- src/lib/MarketplaceGraphClient.ts
> fix: Update query to obtain name owner without being case sensitive

- package-lock.json
- package.json
- src/components/Creations/Creations.tsx
- src/components/Creations/Creations.types.ts
- src/components/Creations/index.ts
- src/components/Pages/MainPage/MainPage.container.ts
- src/components/Pages/MainPage/MainPage.module.css
- src/components/Pages/MainPage/MainPage.tsx
- src/components/Pages/MainPage/MainPage.types.ts
- src/main.tsx
- src/modules/features/selectors.ts
- src/modules/features/types.ts
- src/modules/routing/locations.ts
- src/modules/routing/types.ts
- src/modules/saga.ts
This PR adds the creations tab alongside its feature flag.
Closes #228
Closes #227
> feat: Add the creations tab

- src/components/Assets/Assets.tsx
- src/components/Assets/index.ts
- src/components/Pages/MainPage/MainPage.container.ts
- src/components/Pages/MainPage/MainPage.spec.tsx
- src/components/Pages/MainPage/MainPage.tsx
- src/components/Pages/MainPage/MainPage.types.ts
- src/modules/features/selectors.ts
- src/modules/features/types.ts
- src/modules/routing/types.ts
> feat: add assets tab

- package-lock.json
- package.json
- src/components/Creations/Creations.tsx
- src/components/Modals/CreationsFiltersModal/CreationsFiltersModal.module.css
- src/components/Modals/CreationsFiltersModal/CreationsFiltersModal.tsx
- src/components/Modals/FiltersModal/FiltersModal.module.css
- src/components/NFTFilters/NFTFilters.tsx
This PR updates the DCL UI dependency to have a `CategoryFilter` with mobile support.
> fix: Creations's Category filter styles

- src/components/Assets/Assets.module.css
- src/components/Creations/Creations.module.css
This PR sets the maximum size of the `Assets` and `Creations` rows.
> fix: Max row size

- src/modules/profile/sagas.ts
This PR adds the `all` directive to both profile sagas so they both work together.
Closes #285
> fix: Friends profiles not showing

- src/components/Pages/MainPage/MainPage.module.css
- src/components/Pages/MainPage/MainPage.tsx
This PR adds an animation to the avatar container being hidden when changing between the assets and creations tabs.
#288
> feat: Add avatar container animation

- src/components/Assets/Assets.tsx
- src/components/FriendshipButton/FriendshipButton.spec.tsx
- src/components/FriendshipButton/FriendshipButton.tsx
- src/components/Modals/ConfirmationModal/ConfirmationModal.module.css
- src/components/Modals/FriendsModal/FriendsModal.tsx
- src/modules/profile/utils.spec.ts
- src/modules/profile/utils.ts
- src/modules/translation/locales/en.json
- src/modules/translation/locales/es.json
- src/modules/translation/locales/zh.json
- src/utils/address.ts
- Add clear filters logic when empty result ina ssets page
- Fix name on confirmation modal to match the one in the friends list
> fix: add clear filters logic to assets page

- src/main.tsx
This PR makes the site servible using the new worker at `decentraland.zone/profile`
> feat: Use single site worker in zone

- .github/workflows/set-rollout-by-path-manual.yaml
Add manual github action to test deployment by path flow
> feat: add manual rollout by path

- src/main.tsx
Set basepath depending on host
> fix: basepath for subdomains

- src/components/Pages/MainPage/MainPage.container.ts
- src/components/Pages/MainPage/MainPage.spec.tsx
- src/components/Pages/MainPage/MainPage.tsx
- src/components/Pages/MainPage/MainPage.types.ts
- src/modules/features/selectors.spec.ts
- src/modules/features/selectors.ts
- src/modules/features/types.ts
This PR removes two unused FFs from the site.
> fix: Remove assets and creations FFs

- src/components/Pages/MainPage/MainPage.tsx
This PR fixes a tab redirection issue.
The profile dApps wasn't showing the tab's content and always redirected the user to the overview tab.
> fix: Tabs redirection to overview

- .github/workflows/audit.yml
- .github/workflows/build-release.yaml
- .github/workflows/test.yaml
- package-lock.json
- package.json
This PR updates the build process to use node 20.
> fix: Use node 20

- src/components/Navbar/Navbar.tsx
This PR fixes the auth redirection url not being formed correctly, causing the `auth` dapp to ignore it.
> fix: Auth redirection

- src/@types/theme.d.ts
- src/components/Referrals/ReferralRewardCard/ReferralRewardCard.spec.tsx
- src/components/Referrals/ReferralRewardCard/ReferralRewardCard.styled.ts
- src/components/Referrals/ReferralRewardCard/ReferralRewardCard.tsx
- src/components/Referrals/ReferralRewardCard/constants.ts
- src/components/Referrals/ReferralRewardCard/index.ts
- src/modules/translation/locales/en.json
- src/modules/translation/locales/es.json
- src/modules/translation/locales/zh.json
> feat: add ReferralRewardCard component
